@Library('my-shared-lib') _

node {

    /*stage('Clone') {
    #    gitClone(
     #       'https://github.com/your-username/your-repo.git',
     #       'main',
     #       'git-credentials-id'
     #   )
    #} */

    stage('Build') {
        appClone()
    }

}
